window.CLASS6_DATA = {
  chapters: [
    {
      title: "The Wonderful World of Science",
      type: "general",
      desc: "Introduction to science, its methods, and its role in understanding the natural world.",
      overview: "This chapter introduces students to what science is, how scientists think, and how scientific methods help us explore and understand the world around us.",
      ppt: [
        { type:"title", title:"The Wonderful World of Science", subtitle:"What is science and how does it work?", icon:"🔬" },
        { type:"objectives", title:"Learning Objectives", points:["Understand what science means","Learn about observation and experimentation","Know the steps of the scientific method","Identify different branches of science","Appreciate the role of science in daily life"] },
        { type:"content", title:"What is Science?", points:["Science is a systematic way of understanding the natural world","It involves observation, questioning, and experimentation","Science uses evidence to explain natural phenomena","Science is continuously evolving with new discoveries","Examples: Why does it rain? Why do plants grow towards light?"] },
        { type:"content", title:"Scientific Method", points:["Step 1 — Observe: Notice something interesting in nature","Step 2 — Question: Ask 'why' or 'how' it happens","Step 3 — Hypothesis: Make an educated guess","Step 4 — Experiment: Test your hypothesis","Step 5 — Conclusion: Analyze results and draw conclusions"] },
        { type:"activity", title:"Simple Observation Activity", desc:"Practice the scientific method with a simple everyday activity.", steps:["Take a glass of water and a glass of juice","Observe the colour, smell, and taste of each","Record your observations in a table","Compare properties of both liquids","Write a conclusion about how they differ"] },
        { type:"content", title:"Branches of Science", points:["Physics — Study of forces, motion, energy","Chemistry — Study of matter and its changes","Biology — Study of living organisms","Earth Science — Study of Earth and space","All branches are interconnected and important"] },
        { type:"summary", title:"Chapter Summary", points:["Science = systematic understanding","Observation is the first step","Scientific method has 5 steps","Many branches of science","Science is all around us"] },
        { type:"quiz", title:"Quick Quiz", questions:[{q:"What is the first step of the scientific method?",a:"Observation"},{q:"Name one branch of science.",a:"Physics / Chemistry / Biology"},{q:"Is science ever complete?",a:"No, science is continuously evolving"}] }
      ],
      notes: [
        { heading:"What is Science?", points:["Science is the <span class='note-key'>systematic study</span> of the natural world through observation and experimentation","The word 'science' comes from the Latin word <span class='note-key'>scientia</span> meaning knowledge","Science helps us understand, explain, and predict natural phenomena","Science is based on <span class='note-key'>evidence</span>, not belief or assumption"] },
        { heading:"Scientific Method", points:["<span class='note-key'>Observation</span> — Carefully noticing things using senses or instruments","<span class='note-key'>Hypothesis</span> — A testable explanation or prediction","<span class='note-key'>Experiment</span> — A controlled test to check the hypothesis","<span class='note-key'>Data collection</span> — Recording results accurately","<span class='note-key'>Conclusion</span> — Whether the hypothesis is supported or not"] },
        { heading:"Tools of Science", points:["<span class='note-key'>Ruler</span> — measures length","<span class='note-key'>Thermometer</span> — measures temperature","<span class='note-key'>Microscope</span> — views tiny objects","<span class='note-key'>Balance</span> — measures mass","Scientists record data in tables and graphs for analysis"] },
        { heading:"Branches of Science", points:["<span class='note-key'>Physics</span> — energy, force, motion, light","<span class='note-key'>Chemistry</span> — matter, reactions, elements","<span class='note-key'>Biology</span> — plants, animals, microorganisms","<span class='note-key'>Astronomy</span> — stars, planets, universe","Science is interdisciplinary — branches overlap and support each other"] }
      ],
      solutions: [
        { q:"What do you understand by the term 'science'?", a:"Science is a systematic way of studying and understanding the natural world through careful observation, experimentation, and analysis. It helps us explain why things happen in nature and makes predictions about future events. The knowledge gained through science is always based on evidence and can be tested and verified." },
        { q:"List any four characteristics of science.", a:"(1) Science is based on observation and evidence. (2) Science uses a systematic method (scientific method). (3) Scientific knowledge can be tested and verified by others. (4) Science is ever-evolving — new discoveries can change existing understanding." },
        { q:"What are the different steps in the scientific method?", a:"The steps are: (1) Observation — carefully observing a phenomenon. (2) Question — asking 'why' or 'how'. (3) Hypothesis — forming an educated guess. (4) Experiment — conducting tests to check the hypothesis. (5) Data Analysis — studying the results. (6) Conclusion — deciding whether the hypothesis is supported." },
        { q:"Give two examples of scientific observations from daily life.", a:"(1) Observing that iron left in rain gets rusted (oxidation). (2) Observing that a plant kept near a window grows towards the light (phototropism). These everyday observations can lead to scientific investigations." },
        { q:"What is a hypothesis? Give an example.", a:"A hypothesis is an educated guess or a possible explanation for an observation, which can be tested by experimentation. Example: If a plant is kept in the dark, it will not grow properly (hypothesis) — this can be tested by growing two identical plants, one in light and one in dark, and comparing results." },
        { q:"Name any three branches of science and what each studies.", a:"(1) Physics — Studies matter, energy, forces, and motion. Examples: why things fall, how electricity works. (2) Chemistry — Studies the composition, structure, and properties of matter. Examples: how iron rusts, how food digests. (3) Biology — Studies living organisms. Examples: how plants make food, how the heart pumps blood." },
        { q:"Why is science important in everyday life?", a:"Science helps us in many ways: (1) Medicine and health — doctors use science to treat diseases. (2) Technology — science gave us computers, phones, and vehicles. (3) Agriculture — scientists develop better crops. (4) Environment — science helps us understand and solve pollution. Without science, modern life as we know it would not exist." },
        { q:"Differentiate between observation and inference.", a:"Observation: Directly noticing something using senses or instruments. Example: The water is cold. Inference: A conclusion drawn from an observation. Example: The water is cold because it was kept in a refrigerator. Observation is what you detect; inference is what you conclude from it." }
      ],
      questions: {
        mcq: [
          { q:"Which of the following best defines science?", options:["A subject taught in school","A systematic study of natural world using observation and experiment","A collection of facts","A type of technology"], ans:1, marks:1, explanation:"Science is a systematic approach using observation, experimentation and evidence." },
          { q:"What is the correct order of the scientific method?", options:["Hypothesis → Observation → Experiment → Conclusion","Observation → Hypothesis → Experiment → Conclusion","Experiment → Hypothesis → Observation → Conclusion","Conclusion → Observation → Experiment → Hypothesis"], ans:1, marks:1 },
          { q:"Which branch of science studies living organisms?", options:["Physics","Chemistry","Biology","Astronomy"], ans:2, marks:1 },
          { q:"A hypothesis must be:", options:["Always true","Impossible to test","Testable and falsifiable","Based on imagination only"], ans:2, marks:1 },
          { q:"Which instrument is used to measure temperature?", options:["Ruler","Thermometer","Balance","Microscope"], ans:1, marks:1 }
        ],
        ar: [
          { q:"Assertion (A): Science is based on evidence and observation. Reason (R): Scientists believe things without testing them.", assertion:"Science is based on evidence and observation.", reason:"Scientists believe things without testing them.", a:"(A) is true but (R) is false. Science requires testing and evidence; scientists do not accept claims without verification.", marks:1 },
          { q:"Assertion (A): The scientific method is a systematic process. Reason (R): It involves steps like observation, hypothesis, experiment, and conclusion.", assertion:"The scientific method is a systematic process.", reason:"It involves steps like observation, hypothesis, experiment, and conclusion.", a:"Both (A) and (R) are true, and (R) is the correct explanation of (A).", marks:1 },
          { q:"Assertion (A): Biology and Chemistry are completely unrelated branches of science. Reason (R): Science is divided into separate branches that never interact.", assertion:"Biology and Chemistry are completely unrelated branches of science.", reason:"Science is divided into separate branches that never interact.", a:"Both (A) and (R) are false. Branches of science are interconnected — biochemistry, for example, combines both.", marks:1 }
        ],
        short1: [
          { q:"What is the difference between a scientific law and a scientific theory?", a:"A scientific law describes what happens (e.g., law of gravity — objects fall). A scientific theory explains why it happens (e.g., theory of gravity explains the force behind it). Laws are based on repeated observations; theories explain underlying mechanisms.", marks:2 },
          { q:"Why is it important to record observations carefully?", a:"Careful recording ensures accuracy and allows others to verify the results. If observations are not recorded properly, the experiment cannot be repeated or the data cannot be analysed correctly. It prevents errors and makes science reliable.", marks:2 },
          { q:"Give two ways science has helped improve human life.", a:"(1) Medical science has developed vaccines and medicines that have saved millions of lives. (2) Agricultural science has created high-yield crops and fertilisers, helping feed more people. Science improves quality of life in countless ways.", marks:2 },
          { q:"What is meant by 'controlled experiment'?", a:"A controlled experiment tests only one variable at a time while keeping all other conditions the same. This ensures that the result is due to the variable being tested, not other factors. Example: Testing how light affects plant growth by changing only the amount of light.", marks:2 }
        ],
        short2: [
          { q:"Explain the scientific method with a suitable example.", a:"The scientific method involves: (1) Observation — You notice milk kept outside turns sour. (2) Question — Why does milk become sour? (3) Hypothesis — Bacteria in the air cause milk to sour. (4) Experiment — Keep one sample of milk covered and one open; observe both. (5) Data Analysis — The open milk turns sour faster. (6) Conclusion — Exposure to bacteria in air causes milk to sour. This systematic approach ensures reliable scientific conclusions.", marks:3 },
          { q:"How is science different from other subjects like history or literature?", a:"Science is different because: (1) It is based on objective evidence, not opinions or stories. (2) Scientific claims must be testable and repeatable. (3) Science changes when new evidence is found (e.g., the model of the atom has changed many times). (4) Science uses experiments and instruments to gather data. History and literature may involve interpretation and perspective, while science seeks universal, verifiable truths.", marks:3 }
        ],
        long: [
          { q:"Describe the importance of science in the modern world. Give at least five examples.", a:"Science plays a crucial role in modern life:\n(1) Healthcare — Vaccines, antibiotics, surgery, and diagnostic tools like X-rays are all scientific achievements.\n(2) Communication — Telephones, internet, satellites are possible because of physics and electronics.\n(3) Agriculture — Scientific research has led to better seeds (hybrid varieties), fertilisers, and irrigation methods.\n(4) Transportation — Cars, aeroplanes, and ships work on scientific principles of motion, fuel, and aerodynamics.\n(5) Environment — Science helps us understand climate change, pollution, and how to develop renewable energy.\n(6) Food Preservation — Science gave us refrigeration, pasteurisation, and packaging to keep food safe.\nWithout science, modern civilization would not exist.", marks:5 },
          { q:"What are the qualities of a good scientist? Explain each quality with an example.", a:"A good scientist has these qualities:\n(1) Curiosity — Always asking 'why' and 'how'. Example: Isaac Newton asked why an apple falls down.\n(2) Patience — Scientific experiments take time. Example: Marie Curie spent years researching radioactivity.\n(3) Open-mindedness — Willing to change ideas when evidence demands. Example: Scientists accepted plate tectonics after evidence emerged.\n(4) Accuracy — Recording observations carefully and precisely.\n(5) Creativity — Designing clever experiments and thinking of new ideas.\n(6) Honesty — Reporting results truthfully, even if they don't support the hypothesis.\nThese qualities together make science trustworthy and progressive.", marks:5 }
        ],
        activity: [
          { q:"Activity: Collect five objects from your home. Classify them as natural or man-made. Record your observations in a table and write a short conclusion about which type is more common in your home.", a:"Table should include: Object name | Natural/Man-made | Reason. Examples: stone (natural), plastic bottle (man-made), leaf (natural), glass (man-made), cotton cloth (natural from plant). Conclusion: Most household objects are man-made, showing how science and technology have transformed everyday materials.", marks:3 },
          { q:"Design a simple experiment to show that plants need sunlight to grow. Write the hypothesis, materials, procedure, expected result, and conclusion.", a:"Hypothesis: Plants need sunlight to grow. Materials: Two identical plants, pots with same soil, water. Procedure: Keep Plant A near a sunny window. Keep Plant B in a dark cupboard. Water both equally for 10 days. Observe daily. Expected Result: Plant A grows well with green leaves; Plant B becomes pale yellow and weak. Conclusion: Sunlight is essential for plant growth as it is needed for photosynthesis.", marks:3 }
        ],
        picture: [
          { q:"Look at the diagram of the scientific method cycle. Name any two steps shown and explain their importance.", figure:"Figure: Circular diagram of scientific method with arrows", a:"Steps visible: (1) Observation — It is the starting point. Without careful observation, no scientific question can be formed. (2) Experiment — It tests the hypothesis under controlled conditions to get reliable data. Both steps are essential for valid scientific conclusions.", marks:3 },
          { q:"The picture shows a scientist using a microscope. (a) What is a microscope used for? (b) Name one thing you could observe under a microscope that you cannot see with naked eyes.", figure:"Figure: Scientist using microscope in a laboratory", a:"(a) A microscope is used to view very tiny objects that cannot be seen with the naked eye, such as cells, bacteria, and microorganisms. (b) One example: Blood cells — you can see red blood cells, white blood cells, and platelets clearly under a microscope.", marks:2 }
        ],
        casestudy: [
          { q:"Case Study", passage:"Riya noticed that the bread kept in her kitchen became mouldy after three days, while the bread kept in the refrigerator stayed fresh for more than a week. She wanted to find out why. She set up an experiment with two slices of bread from the same loaf — one kept at room temperature and one in the refrigerator — and observed them every day.", subqs:[{q:"What observation led Riya to conduct this experiment?",a:"Riya observed that bread kept at room temperature became mouldy in 3 days while refrigerated bread stayed fresh for over a week.",marks:1},{q:"State the hypothesis Riya might have formed.",a:"Hypothesis: Low temperature (refrigeration) slows down the growth of mould on bread.",marks:1},{q:"What conclusion can be drawn from her experiment?",a:"Low temperature inhibits the growth of mould (fungi). Cold conditions slow microbial activity, preserving food for longer.",marks:2},{q:"Name the branch of science that would help explain why mould grew on the bread.",a:"Biology (Microbiology) — the study of microorganisms like mould fungi.",marks:1}], marks:5 },
          { q:"Case Study", passage:"Arjun's teacher asked the class to find out if sugar dissolves faster in hot water or cold water. Arjun took two glasses — one with hot water and one with cold water — added one teaspoon of sugar to each, stirred them equally, and observed how quickly the sugar dissolved.", subqs:[{q:"Identify the variable being tested in this experiment.",a:"The variable being tested is temperature of water (hot vs cold).",marks:1},{q:"What should Arjun keep the same (constant) in both glasses?",a:"Amount of water, amount of sugar, stirring speed and time.",marks:1},{q:"What result do you expect? Give a scientific reason.",a:"Sugar will dissolve faster in hot water because heat increases the kinetic energy of water molecules, causing them to move faster and break down sugar particles more quickly.",marks:2},{q:"Is this experiment a fair test? Why?",a:"Yes, if all other variables are kept constant and only temperature is changed, it is a fair and controlled experiment.",marks:1}], marks:5 }
        ]
      },
      worksheet: {
        sectionA: [
          { q:"Which of the following is the correct first step of the scientific method?", options:["Experiment","Hypothesis","Observation","Conclusion"], ans:2 },
          { q:"The study of living organisms is called:", options:["Physics","Astronomy","Chemistry","Biology"], ans:3 },
          { q:"A hypothesis is best described as:", options:["A proven fact","A testable educated guess","A conclusion","A law"], ans:1 },
          { q:"Which instrument measures temperature?", options:["Microscope","Ruler","Thermometer","Balance"], ans:2 },
          { q:"Science is based on:", options:["Belief","Evidence and observation","Tradition","Imagination"], ans:1 }
        ],
        sectionB: [
          { q:"What is a controlled experiment? Give one example.", a:"A controlled experiment tests only one variable while keeping all others constant. Example: Testing plant growth in light vs dark, with same soil and water.", marks:2 },
          { q:"Give two examples of how science has helped humans.", a:"(1) Development of vaccines to prevent diseases. (2) Creation of high-yield crops to prevent hunger.", marks:2 }
        ],
        sectionC: [
          { q:"Explain the five steps of the scientific method with a real-life example.", a:"(1) Observation — Milk left out turns sour. (2) Question — Why does milk sour? (3) Hypothesis — Bacteria cause souring. (4) Experiment — Cover one sample, leave other open. (5) Conclusion — Open milk sours due to bacteria. Each step ensures reliable results.", marks:3 },
          { q:"What are three qualities of a good scientist? Explain each briefly.", a:"(1) Curiosity — Asks questions and explores why things happen. (2) Accuracy — Records data carefully without errors. (3) Honesty — Reports results truthfully even if they disprove the hypothesis.", marks:3 }
        ],
        sectionD: [
          { passage:"Maya noticed that plants near her window grew tilting towards the glass. She wondered if plants grow towards light. She placed one plant near a window and one in the middle of the room and observed for 14 days.", subqs:[{q:"State Maya's observation.",a:"Plants near the window grow tilting towards the glass/light.",marks:1},{q:"Write a hypothesis for Maya's experiment.",a:"Plants grow in the direction of light source (phototropism).",marks:1},{q:"What results would you expect after 14 days?",a:"Plant near window tilts towards light; plant in middle grows upright.",marks:2},{q:"Name the scientific term for plant movement towards light.",a:"Phototropism.",marks:1}], marks:5 }
        ]
      }
    }
  ]
};
